// Package signal provides a client for communicating with the WebRTC signaling server.
package signal

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"
)

// SessionDescription matches the data structure used by the signaling server.
type SessionDescription struct {
	Type string `json:"type"`
	SDP  string `json:"sdp"`
}

// Client manages communication with the signaling server.
type Client struct {
	baseURL    string
	httpClient *http.Client
}

// NewClient creates a new client for the signaling server.
func NewClient(baseURL string) *Client {
	return &Client{
		baseURL: baseURL,
		httpClient: &http.Client{
			Timeout: 10 * time.Second, // A request timeout is a good practice.
		},
	}
}

// CreateSession sends the host's offer to the server to create a new session.
// It returns the unique session ID generated by the server.
func (c *Client) CreateSession(offer SessionDescription) (string, error) {
	payload, err := json.Marshal(offer)
	if err != nil {
		return "", fmt.Errorf("failed to marshal offer: %w", err)
	}

	req, err := http.NewRequest("POST", c.baseURL+"/session", bytes.NewReader(payload))
	if err != nil {
		return "", fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to send offer: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		return "", fmt.Errorf("server returned non-201 status: %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}

	return string(body), nil
}

// GetOffer retrieves the host's offer for a given session ID.
func (c *Client) GetOffer(sessionID string) (*SessionDescription, error) {
	resp, err := c.httpClient.Get(c.baseURL + "/session/" + sessionID)
	if err != nil {
		return nil, fmt.Errorf("failed to get offer: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("server returned non-200 status: %s", resp.Status)
	}

	var offer SessionDescription
	if err := json.NewDecoder(resp.Body).Decode(&offer); err != nil {
		return nil, fmt.Errorf("failed to decode offer: %w", err)
	}

	return &offer, nil
}

// PostAnswer sends the joiner's answer to the server for a given session.
func (c *Client) PostAnswer(sessionID string, answer SessionDescription) error {
	payload, err := json.Marshal(answer)
	if err != nil {
		return fmt.Errorf("failed to marshal answer: %w", err)
	}

	req, err := http.NewRequest("POST", c.baseURL+"/session/"+sessionID, bytes.NewReader(payload))
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send answer: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("server returned non-200 status for answer: %s", resp.Status)
	}

	return nil
}

// PollForAnswer periodically asks the server for the joiner's answer.
// This is used by the host after creating a session.
// PollForAnswer periodically asks the server for the joiner's answer.
func (c *Client) PollForAnswer(ctx context.Context, sessionID string) (*SessionDescription, error) {
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	// The URL used for polling, which correctly identifies this client as the host.
	pollingURL := fmt.Sprintf("%s/session/%s?client=host", c.baseURL, sessionID)

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			// CORRECTED: Use the pollingURL variable here.
			resp, err := c.httpClient.Get(pollingURL)
			if err != nil {
				// This error is expected if the server is down, just log and continue.
				log.Printf("Polling error: %v. Retrying...", err)
				continue
			}

			// The server now correctly sends 204 No Content until the answer is ready.
			if resp.StatusCode == http.StatusNoContent {
				resp.Body.Close()
				continue // Keep polling.
			}

			if resp.StatusCode == http.StatusOK {
				var answer SessionDescription
				if err := json.NewDecoder(resp.Body).Decode(&answer); err != nil {
					resp.Body.Close()
					return nil, fmt.Errorf("failed to decode answer: %w", err)
				}
				resp.Body.Close()
				return &answer, nil
			}

			// Handle any other unexpected statuses from the server.
			log.Printf("Polling received unexpected status: %s", resp.Status)
			resp.Body.Close()
		}
	}
}
