// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HostSession(arg1) {
  return window['go']['main']['App']['HostSession'](arg1);
}

export function JoinSession(arg1, arg2) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
