// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HostSession(arg1:string):Promise<string>;

export function JoinSession(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;
